// Code generated by mockery. DO NOT EDIT.

package stmtuci

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	statement "github.com/DenysonJ/financial-wallet/internal/domain/statement"

	vo "github.com/DenysonJ/financial-wallet/pkg/vo"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, stmt, accountID
func (_m *MockRepository) Create(ctx context.Context, stmt *statement.Statement, accountID vo.ID) (int64, error) {
	ret := _m.Called(ctx, stmt, accountID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *statement.Statement, vo.ID) (int64, error)); ok {
		return rf(ctx, stmt, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *statement.Statement, vo.ID) int64); ok {
		r0 = rf(ctx, stmt, accountID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *statement.Statement, vo.ID) error); ok {
		r1 = rf(ctx, stmt, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - stmt *statement.Statement
//   - accountID vo.ID
func (_e *MockRepository_Expecter) Create(ctx interface{}, stmt interface{}, accountID interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, stmt, accountID)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, stmt *statement.Statement, accountID vo.ID)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*statement.Statement), args[2].(vo.ID))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 int64, _a1 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context.Context, *statement.Statement, vo.ID) (int64, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockRepository) FindByID(ctx context.Context, id vo.ID) (*statement.Statement, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *statement.Statement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, vo.ID) (*statement.Statement, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, vo.ID) *statement.Statement); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*statement.Statement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, vo.ID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id vo.ID
func (_e *MockRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockRepository_FindByID_Call {
	return &MockRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockRepository_FindByID_Call) Run(run func(ctx context.Context, id vo.ID)) *MockRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(vo.ID))
	})
	return _c
}

func (_c *MockRepository_FindByID_Call) Return(_a0 *statement.Statement, _a1 error) *MockRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_FindByID_Call) RunAndReturn(run func(context.Context, vo.ID) (*statement.Statement, error)) *MockRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// HasReversal provides a mock function with given fields: ctx, statementID
func (_m *MockRepository) HasReversal(ctx context.Context, statementID vo.ID) (bool, error) {
	ret := _m.Called(ctx, statementID)

	if len(ret) == 0 {
		panic("no return value specified for HasReversal")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, vo.ID) (bool, error)); ok {
		return rf(ctx, statementID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, vo.ID) bool); ok {
		r0 = rf(ctx, statementID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, vo.ID) error); ok {
		r1 = rf(ctx, statementID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_HasReversal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasReversal'
type MockRepository_HasReversal_Call struct {
	*mock.Call
}

// HasReversal is a helper method to define mock.On call
//   - ctx context.Context
//   - statementID vo.ID
func (_e *MockRepository_Expecter) HasReversal(ctx interface{}, statementID interface{}) *MockRepository_HasReversal_Call {
	return &MockRepository_HasReversal_Call{Call: _e.mock.On("HasReversal", ctx, statementID)}
}

func (_c *MockRepository_HasReversal_Call) Run(run func(ctx context.Context, statementID vo.ID)) *MockRepository_HasReversal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(vo.ID))
	})
	return _c
}

func (_c *MockRepository_HasReversal_Call) Return(_a0 bool, _a1 error) *MockRepository_HasReversal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_HasReversal_Call) RunAndReturn(run func(context.Context, vo.ID) (bool, error)) *MockRepository_HasReversal_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockRepository) List(ctx context.Context, filter statement.ListFilter) (*statement.ListResult, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *statement.ListResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, statement.ListFilter) (*statement.ListResult, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, statement.ListFilter) *statement.ListResult); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*statement.ListResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, statement.ListFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter statement.ListFilter
func (_e *MockRepository_Expecter) List(ctx interface{}, filter interface{}) *MockRepository_List_Call {
	return &MockRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockRepository_List_Call) Run(run func(ctx context.Context, filter statement.ListFilter)) *MockRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(statement.ListFilter))
	})
	return _c
}

func (_c *MockRepository_List_Call) Return(_a0 *statement.ListResult, _a1 error) *MockRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_List_Call) RunAndReturn(run func(context.Context, statement.ListFilter) (*statement.ListResult, error)) *MockRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBatch provides a mock function with given fields: ctx, stmts, accountID
func (_m *MockRepository) CreateBatch(ctx context.Context, stmts []*statement.Statement, accountID vo.ID) (int64, error) {
	ret := _m.Called(ctx, stmts, accountID)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []*statement.Statement, vo.ID) (int64, error)); ok {
		return rf(ctx, stmts, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []*statement.Statement, vo.ID) int64); ok {
		r0 = rf(ctx, stmts, accountID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []*statement.Statement, vo.ID) error); ok {
		r1 = rf(ctx, stmts, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindExternalIDs provides a mock function with given fields: ctx, accountID, externalIDs
func (_m *MockRepository) FindExternalIDs(ctx context.Context, accountID vo.ID, externalIDs []string) (map[string]bool, error) {
	ret := _m.Called(ctx, accountID, externalIDs)

	if len(ret) == 0 {
		panic("no return value specified for FindExternalIDs")
	}

	var r0 map[string]bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, vo.ID, []string) (map[string]bool, error)); ok {
		return rf(ctx, accountID, externalIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, vo.ID, []string) map[string]bool); ok {
		r0 = rf(ctx, accountID, externalIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]bool)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, vo.ID, []string) error); ok {
		r1 = rf(ctx, accountID, externalIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
