// Code generated by mockery. DO NOT EDIT.

package taguci

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	tag "github.com/DenysonJ/financial-wallet/internal/domain/tag"

	vo "github.com/DenysonJ/financial-wallet/pkg/vo"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, t
func (_m *MockRepository) Create(ctx context.Context, t *tag.Tag) error {
	ret := _m.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *tag.Tag) error); ok {
		r0 = rf(ctx, t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - t *tag.Tag
func (_e *MockRepository_Expecter) Create(ctx interface{}, t interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, t)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, t *tag.Tag)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*tag.Tag))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context.Context, *tag.Tag) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockRepository) Delete(ctx context.Context, id vo.ID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, vo.ID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id vo.ID
func (_e *MockRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRepository_Delete_Call) Run(run func(ctx context.Context, id vo.ID)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(vo.ID))
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(_a0 error) *MockRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(context.Context, vo.ID) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockRepository) FindByID(ctx context.Context, id vo.ID) (*tag.Tag, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *tag.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, vo.ID) (*tag.Tag, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, vo.ID) *tag.Tag); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tag.Tag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, vo.ID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id vo.ID
func (_e *MockRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockRepository_FindByID_Call {
	return &MockRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockRepository_FindByID_Call) Run(run func(ctx context.Context, id vo.ID)) *MockRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(vo.ID))
	})
	return _c
}

func (_c *MockRepository_FindByID_Call) Return(_a0 *tag.Tag, _a1 error) *MockRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_FindByID_Call) RunAndReturn(run func(context.Context, vo.ID) (*tag.Tag, error)) *MockRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindManyVisible provides a mock function with given fields: ctx, ids, userID
func (_m *MockRepository) FindManyVisible(ctx context.Context, ids []vo.ID, userID vo.ID) ([]*tag.Tag, error) {
	ret := _m.Called(ctx, ids, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindManyVisible")
	}

	var r0 []*tag.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []vo.ID, vo.ID) ([]*tag.Tag, error)); ok {
		return rf(ctx, ids, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []vo.ID, vo.ID) []*tag.Tag); ok {
		r0 = rf(ctx, ids, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*tag.Tag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []vo.ID, vo.ID) error); ok {
		r1 = rf(ctx, ids, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_FindManyVisible_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindManyVisible'
type MockRepository_FindManyVisible_Call struct {
	*mock.Call
}

// FindManyVisible is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []vo.ID
//   - userID vo.ID
func (_e *MockRepository_Expecter) FindManyVisible(ctx interface{}, ids interface{}, userID interface{}) *MockRepository_FindManyVisible_Call {
	return &MockRepository_FindManyVisible_Call{Call: _e.mock.On("FindManyVisible", ctx, ids, userID)}
}

func (_c *MockRepository_FindManyVisible_Call) Run(run func(ctx context.Context, ids []vo.ID, userID vo.ID)) *MockRepository_FindManyVisible_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]vo.ID), args[2].(vo.ID))
	})
	return _c
}

func (_c *MockRepository_FindManyVisible_Call) Return(_a0 []*tag.Tag, _a1 error) *MockRepository_FindManyVisible_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_FindManyVisible_Call) RunAndReturn(run func(context.Context, []vo.ID, vo.ID) ([]*tag.Tag, error)) *MockRepository_FindManyVisible_Call {
	_c.Call.Return(run)
	return _c
}

// FindVisible provides a mock function with given fields: ctx, id, userID
func (_m *MockRepository) FindVisible(ctx context.Context, id vo.ID, userID vo.ID) (*tag.Tag, error) {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindVisible")
	}

	var r0 *tag.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, vo.ID, vo.ID) (*tag.Tag, error)); ok {
		return rf(ctx, id, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, vo.ID, vo.ID) *tag.Tag); ok {
		r0 = rf(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tag.Tag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, vo.ID, vo.ID) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_FindVisible_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindVisible'
type MockRepository_FindVisible_Call struct {
	*mock.Call
}

// FindVisible is a helper method to define mock.On call
//   - ctx context.Context
//   - id vo.ID
//   - userID vo.ID
func (_e *MockRepository_Expecter) FindVisible(ctx interface{}, id interface{}, userID interface{}) *MockRepository_FindVisible_Call {
	return &MockRepository_FindVisible_Call{Call: _e.mock.On("FindVisible", ctx, id, userID)}
}

func (_c *MockRepository_FindVisible_Call) Run(run func(ctx context.Context, id vo.ID, userID vo.ID)) *MockRepository_FindVisible_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(vo.ID), args[2].(vo.ID))
	})
	return _c
}

func (_c *MockRepository_FindVisible_Call) Return(_a0 *tag.Tag, _a1 error) *MockRepository_FindVisible_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_FindVisible_Call) RunAndReturn(run func(context.Context, vo.ID, vo.ID) (*tag.Tag, error)) *MockRepository_FindVisible_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockRepository) List(ctx context.Context, filter tag.ListFilter) ([]*tag.Tag, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*tag.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, tag.ListFilter) ([]*tag.Tag, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, tag.ListFilter) []*tag.Tag); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*tag.Tag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, tag.ListFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter tag.ListFilter
func (_e *MockRepository_Expecter) List(ctx interface{}, filter interface{}) *MockRepository_List_Call {
	return &MockRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockRepository_List_Call) Run(run func(ctx context.Context, filter tag.ListFilter)) *MockRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(tag.ListFilter))
	})
	return _c
}

func (_c *MockRepository_List_Call) Return(_a0 []*tag.Tag, _a1 error) *MockRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_List_Call) RunAndReturn(run func(context.Context, tag.ListFilter) ([]*tag.Tag, error)) *MockRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, t
func (_m *MockRepository) Update(ctx context.Context, t *tag.Tag) error {
	ret := _m.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *tag.Tag) error); ok {
		r0 = rf(ctx, t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - t *tag.Tag
func (_e *MockRepository_Expecter) Update(ctx interface{}, t interface{}) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update", ctx, t)}
}

func (_c *MockRepository_Update_Call) Run(run func(ctx context.Context, t *tag.Tag)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*tag.Tag))
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(_a0 error) *MockRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(context.Context, *tag.Tag) error) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
