// Code generated by mockery. DO NOT EDIT.

package middlewaremock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPermissionLoader is an autogenerated mock type for the PermissionLoader type
type MockPermissionLoader struct {
	mock.Mock
}

type MockPermissionLoader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPermissionLoader) EXPECT() *MockPermissionLoader_Expecter {
	return &MockPermissionLoader_Expecter{mock: &_m.Mock}
}

// GetPermissions provides a mock function with given fields: ctx, userID
func (_m *MockPermissionLoader) GetPermissions(ctx context.Context, userID string) ([]string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPermissions")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPermissionLoader_GetPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPermissions'
type MockPermissionLoader_GetPermissions_Call struct {
	*mock.Call
}

// GetPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockPermissionLoader_Expecter) GetPermissions(ctx interface{}, userID interface{}) *MockPermissionLoader_GetPermissions_Call {
	return &MockPermissionLoader_GetPermissions_Call{Call: _e.mock.On("GetPermissions", ctx, userID)}
}

func (_c *MockPermissionLoader_GetPermissions_Call) Run(run func(ctx context.Context, userID string)) *MockPermissionLoader_GetPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPermissionLoader_GetPermissions_Call) Return(_a0 []string, _a1 error) *MockPermissionLoader_GetPermissions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPermissionLoader_GetPermissions_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *MockPermissionLoader_GetPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoles provides a mock function with given fields: ctx, userID
func (_m *MockPermissionLoader) GetRoles(ctx context.Context, userID string) ([]string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetRoles")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPermissionLoader_GetRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoles'
type MockPermissionLoader_GetRoles_Call struct {
	*mock.Call
}

// GetRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockPermissionLoader_Expecter) GetRoles(ctx interface{}, userID interface{}) *MockPermissionLoader_GetRoles_Call {
	return &MockPermissionLoader_GetRoles_Call{Call: _e.mock.On("GetRoles", ctx, userID)}
}

func (_c *MockPermissionLoader_GetRoles_Call) Run(run func(ctx context.Context, userID string)) *MockPermissionLoader_GetRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPermissionLoader_GetRoles_Call) Return(_a0 []string, _a1 error) *MockPermissionLoader_GetRoles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPermissionLoader_GetRoles_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *MockPermissionLoader_GetRoles_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPermissionLoader creates a new instance of MockPermissionLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPermissionLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPermissionLoader {
	mock := &MockPermissionLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
