// Code generated by mockery. DO NOT EDIT.

package middlewaremock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPermissionRepository is an autogenerated mock type for the PermissionRepository type
type MockPermissionRepository struct {
	mock.Mock
}

type MockPermissionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPermissionRepository) EXPECT() *MockPermissionRepository_Expecter {
	return &MockPermissionRepository_Expecter{mock: &_m.Mock}
}

// GetUserPermissions provides a mock function with given fields: ctx, userID
func (_m *MockPermissionRepository) GetUserPermissions(ctx context.Context, userID string) ([]string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPermissions")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPermissionRepository_GetUserPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserPermissions'
type MockPermissionRepository_GetUserPermissions_Call struct {
	*mock.Call
}

// GetUserPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockPermissionRepository_Expecter) GetUserPermissions(ctx interface{}, userID interface{}) *MockPermissionRepository_GetUserPermissions_Call {
	return &MockPermissionRepository_GetUserPermissions_Call{Call: _e.mock.On("GetUserPermissions", ctx, userID)}
}

func (_c *MockPermissionRepository_GetUserPermissions_Call) Run(run func(ctx context.Context, userID string)) *MockPermissionRepository_GetUserPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPermissionRepository_GetUserPermissions_Call) Return(_a0 []string, _a1 error) *MockPermissionRepository_GetUserPermissions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPermissionRepository_GetUserPermissions_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *MockPermissionRepository_GetUserPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserRoles provides a mock function with given fields: ctx, userID
func (_m *MockPermissionRepository) GetUserRoles(ctx context.Context, userID string) ([]string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRoles")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPermissionRepository_GetUserRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserRoles'
type MockPermissionRepository_GetUserRoles_Call struct {
	*mock.Call
}

// GetUserRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockPermissionRepository_Expecter) GetUserRoles(ctx interface{}, userID interface{}) *MockPermissionRepository_GetUserRoles_Call {
	return &MockPermissionRepository_GetUserRoles_Call{Call: _e.mock.On("GetUserRoles", ctx, userID)}
}

func (_c *MockPermissionRepository_GetUserRoles_Call) Run(run func(ctx context.Context, userID string)) *MockPermissionRepository_GetUserRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPermissionRepository_GetUserRoles_Call) Return(_a0 []string, _a1 error) *MockPermissionRepository_GetUserRoles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPermissionRepository_GetUserRoles_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *MockPermissionRepository_GetUserRoles_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPermissionRepository creates a new instance of MockPermissionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPermissionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPermissionRepository {
	mock := &MockPermissionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
